spring.application.name=Orbit

spring.config.import=application-secret.properties

server.port=80

spring.datasource.url=${db.url}
spring.datasource.username=${db.username}
spring.datasource.password=${db.password}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
mybatis.mapper-locations=classpath:mappers/*-mapper.xml

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=100MB

spring.cloud.gcp.credentials.location=file:src/main/resources/GCP_Key.json
spring.cloud.gcp.bucket = orbit-private
gcs.bucket.url=https://storage.googleapis.com/orbit-private

jwt.expiration = 86400000

spring.ai.google.genai.api-key=${api-key}
spring.ai.google.genai.chat.options.model=gemini-3.1-flash-lite

# OpenAI 비활성화
spring.ai.openai.api-key=DISABLED
spring.autoconfigure.exclude=\
  org.springframework.ai.model.openai.autoconfigure.OpenAiAudioSpeechAutoConfiguration,\
  org.springframework.ai.model.openai.autoconfigure.OpenAiAutoConfiguration
  
spring.profiles.include=secret
encryption.aes256.secret-key=${aes.secret.key}
encryption.aes256.iv=${aes.iv}

## 파이썬 API 서버 URL
#python.api.url=http://175.207.143.61:8000

# 파이썬 API 서버 URL (학원)
python.api.url=http://10.10.55.139:8000

# 이메일 인증
spring.mail.host=smtp.naver.com
spring.mail.port=465

spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.naver.com

# 환경 변수에서 ALLOWED_ORIGIN을 찾아서 넣고, 없으면 기본값으로 로컬 주소를 쓰겠다는 뜻
app.cors.allowed-origin=${ALLOWED_ORIGIN:http://localhost:5173}
app.mail.from=${MAIL_USERNAME:}